### PR TITLE
remove countdash application

### PR DESCRIPTION
**Pull request by tgross**
This application is canonically described elsewhere

### CODE REVIEW

**Review by schmichael — APPROVED** [review]
Should we link to the canonical location from the root README? I'd hate for something to link someone here and for it to be a deadend.

**Comment by tgross** [comment]
> Should we link to the canonical location from the root README? I'd hate for something to link someone here and for it to be a deadend.

Will do... as soon as I can find it :grinning:

**Comment by lgfa29** [comment]
Source code is in https://github.com/hashicorp/demo-consul-101/tree/main/services. Dockerfile is... 🤷

**Comment by tgross** [comment]
Added notes to the README explaining what's in the repo and where Countdash can be found (for now)

**Pull request merged**
